version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: studytime-backoffice-web
    volumes:
      - ".:/app"
    ports:
      - "81:80"
    tty: true
